In [2]:
#1.3.1
import numpy as np

board = np.arange(1, 65).reshape(8, 8) % 2
print(board)

[[1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]]


In [3]:
#1.3.2
import numpy as np

matrix = np.arange(0, 25).reshape(5, 5) % 5
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [6]:
#1.3.3
import numpy as np

array = np.random.random((3, 3, 3))
print(array)

[[[0.26653049 0.60545646 0.77100562]
  [0.43173942 0.97706394 0.02674143]
  [0.157289   0.931885   0.23960697]]

 [[0.35309136 0.33953715 0.85517057]
  [0.98470318 0.84699414 0.82606766]
  [0.72594923 0.38682246 0.2497464 ]]

 [[0.66069212 0.55244335 0.72952642]
  [0.47005892 0.1564885  0.56092787]
  [0.7475924  0.78160825 0.87977079]]]


In [16]:
#1.3.4
import numpy as np

size = (5, 5)
matrix = np.ones(size)
matrix[1:-1, 1:-1] = np.zeros((size[0] - 2, size[1] - 2))
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
#1.3.5
import numpy as np

size = 10
array = np.random.random(size)
array = np.sort(array)[::-1]
print(array)

[0.96377399 0.90848761 0.88301617 0.7197506  0.71821136 0.49458941
 0.38350629 0.26147378 0.21980298 0.05243557]


In [30]:
#1.3.6
import numpy as np

size = (1, 2, 3)
matrix = np.random.random(size)
print("shape -", matrix.shape)
print("size -", matrix.size)
print("dimension -", matrix.ndim)

shape - (1, 2, 3)
size - 6
dimension - 3


In [51]:
#2.3.1
import pandas as pd

def distance(a, b):
    return ((a["x"] - b["x"])**2 +
            (a["y"] - b["y"])**2 +
            (a["z"] - b["z"])**2)**0.5

p1_coords = [1, 2, 3]
p2_coords = [3, 2, 1]

p1 = pd.Series(data=p1_coords, index=["x", "y", "z"])
p2 = pd.Series(data=p2_coords, index=["x", "y", "z"])
distance(p1, p2)

2.8284271247461903

In [53]:
#2.3.2
import pandas as pd

movies = pd.read_csv("data/IMDB_Top_250_Movies.csv")
movies

rank                      name  year  rating                       genre  \
0       1  The Shawshank Redemption  1994     9.3                       Drama   
1       2             The Godfather  1972     9.2                 Crime,Drama   
2       3           The Dark Knight  2008     9.0          Action,Crime,Drama   
3       4     The Godfather Part II  1974     9.0                 Crime,Drama   
4       5              12 Angry Men  1957     9.0                 Crime,Drama   
..    ...                       ...   ...     ...                         ...   
245   246                  The Help  2011     8.1                       Drama   
246   247               Dersu Uzala  1975     8.2   Adventure,Biography,Drama   
247   248                   Aladdin  1992     8.0  Animation,Adventure,Comedy   
248   249                    Gandhi  1982     8.0     Biography,Drama,History   
249   250        Dances with Wolves  1990     8.0     Adventure,Drama,Western   

    certificate run_time                                            tagline  \
0             R   2h 22m  Fear can hold you prisoner. Hope can set you f...   
1             R   2h 55m                         An offer you can't refuse.   
2         PG-13   2h 32m                                    Why So Serious?   
3             R   3h 22m       All the power on earth can't change destiny.   
4      Approved   1h 36m  Life Is In Their Hands -- Death Is On Their Mi...   
..          ...      ...                                                ...   
245       PG-13   2h 26m                      Change begins with a whisper.   
246           G   2h 22m  There is man and beast at nature's mercy. Ther...   
247           G   1h 30m                     Wish granted! (DVD re-release)   
248          PG   3h 11m             His Triumph Changed The World Forever.   
249       PG-13    3h 1m  Inside everyone is a frontier waiting to be di...   

            budget     box_office  \
0         25000000       28884504   
1          6000000      250341816   
2        185000000     1006234167   
3         13000000       47961919   
4           350000            955   
..             ...            ...   
245       25000000      216639112   
246        4000000          14480   
247  Not Available  Not Available   
248       22000000       52767889   
249       22000000      424208848   

                                                 casts  \
0    Tim Robbins,Morgan Freeman,Bob Gunton,William ...   
1    Marlon Brando,Al Pacino,James Caan,Diane Keato...   
2    Christian Bale,Heath Ledger,Aaron Eckhart,Mich...   
3    Al Pacino,Robert De Niro,Robert Duvall,Diane K...   
4    Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...   
..                                                 ...   
245  Viola Davis,Emma Stone,Octavia Spencer,Bryce D...   
246  Maksim Munzuk,Yuriy Solomin,Mikhail Bychkov,Vl...   
247  Scott Weinger,Robin Williams,Linda Larkin,Jona...   
248  Ben Kingsley,John Gielgud,Rohini Hattangadi,Ro...   
249  Kevin Costner,Mary McDonnell,Graham Greene,Rod...   

                    directors                                          writers  
0              Frank Darabont                      Stephen King,Frank Darabont  
1        Francis Ford Coppola                  Mario Puzo,Francis Ford Coppola  
2           Christopher Nolan  Jonathan Nolan,Christopher Nolan,David S. Goyer  
3        Francis Ford Coppola                  Francis Ford Coppola,Mario Puzo  
4                Sidney Lumet                                    Reginald Rose  
..                        ...                                              ...  
245               Tate Taylor                     Tate Taylor,Kathryn Stockett  
246            Akira Kurosawa    Akira Kurosawa,Yuriy Nagibin,Vladimir Arsenev  
247  Ron Clements,John Musker             Ron Clements,John Musker,Ted Elliott  
248      Richard Attenborough                                      John Briley  
249             Kevin Costner                     

In [59]:
#2.3.3
import pandas as pd

print(movies.head(2))
print("-------------------------------------------------------------------")
print(movies.tail(3))
print("-------------------------------------------------------------------")
print(movies.shape)
print("-------------------------------------------------------------------")
print(movies.describe())
print("-------------------------------------------------------------------")
print(movies.iloc[1:4])
print("-------------------------------------------------------------------")
print(movies[movies['rating'] == 9.0].head(2))

   rank                      name  year  rating        genre certificate  \
0     1  The Shawshank Redemption  1994     9.3        Drama           R   
1     2             The Godfather  1972     9.2  Crime,Drama           R   

  run_time                                            tagline    budget  \
0   2h 22m  Fear can hold you prisoner. Hope can set you f...  25000000   
1   2h 55m                         An offer you can't refuse.   6000000   

  box_office                                              casts  \
0   28884504  Tim Robbins,Morgan Freeman,Bob Gunton,William ...   
1  250341816  Marlon Brando,Al Pacino,James Caan,Diane Keato...   

              directors                          writers  
0        Frank Darabont      Stephen King,Frank Darabont  
1  Francis Ford Coppola  Mario Puzo,Francis Ford Coppola  
-------------------------------------------------------------------
     rank                name  year  rating                       genre  \
247   248             A

In [46]:
#3.3.2
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

min_max_scaler = MinMaxScaler()
z_scaler = StandardScaler()

iris = pd.read_csv("data/iris.csv")
iris.iloc[:, 0:1] = min_max_scaler.fit_transform(iris.iloc[:, 0:1].to_numpy())
iris.iloc[:, 1:2] = z_scaler.fit_transform(iris.iloc[:, 1:2].to_numpy())

iris

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]